# Generated by Django 5.2.8 on 2025-11-06 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Asignatura')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
            },
        ),
        migrations.CreateModel(
            name='TipoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Tipo de Material (Subcarpeta)')),
            ],
            options={
                'verbose_name': 'Tipo de Material',
                'verbose_name_plural': 'Tipos de Material',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título del Recurso')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción o Resumen')),
                ('archivo', models.FileField(upload_to='materiales/', verbose_name='Archivo Digital')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.asignatura', verbose_name='Asignatura')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
                ('tipo_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.tipomaterial', verbose_name='Categoría (Subcarpeta)')),
            ],
            options={
                'verbose_name': 'Material Educativo',
                'verbose_name_plural': 'Materiales Educativos',
                'ordering': ['asignatura__nombre', 'titulo'],
            },
        ),
    ]
