# Generated by Django 5.2.7 on 2025-10-30 17:11

import json
import os
from django.db import migrations

def cargar_ejercicios(apps, schema_editor):

    Ejercicios = apps.get_model('ejercicios', 'Ejercicios')
    migration_dir = os.path.dirname(__file__)
    json_dir = os.path.join(migration_dir, 'data') 

    # Read and load data from JSON files
    for filename in os.listdir(json_dir):
        file_path = os.path.join(json_dir, filename)
        print(f'Loading data from {file_path}')
        with open(file_path, 'r', encoding='utf-8') as file:
            data = json.load(file)
            for item in data:
                Ejercicios.objects.create(
                    topico=item['topico'],
                    enunciado=item['enunciado'],
                    ejercicio=item['formula'],
                    respuesta_correcta=item['respuesta'],
                    alternativa1=item['alternativa_1'],
                    alternativa2=item['alternativa_2'],
                    alternativa3=item['alternativa_3']
                )

def limpiar_ejercicios(apps, schema_editor):
    ejercicios = apps.get_model('ejercicios', 'Ejercicios') 
    ejercicios.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(cargar_ejercicios, limpiar_ejercicios)
    ]
