# Generated by Django 5.2.7 on 2025-10-30 17:11

from django.db import migrations

def cargar_ejercicios(apps, schema_editor):

    Ejercicios = apps.get_model('ejercicios', 'Ejercicios')

    ejercicios_calculo = [
    {
        "enunciado": "Encuentra el límite de la función cuando x tiende a 2",
        "ejercicio": "\\lim_{x \\to 2} (3x + 1)",
        "respuesta_correcta": "7",
        "alternativa_incorrecta1": "5",
        "alternativa_incorrecta2": "8",
        "topico": "calculo infinitesimal"
    },
    {
        "enunciado": "Calcula la derivada de la función",
        "ejercicio": "f(x) = x^2 + 3x - 5",
        "respuesta_correcta": "f'(x) = 2x + 3",
        "alternativa_incorrecta1": "f'(x) = 2x",
        "alternativa_incorrecta2": "f'(x) = x + 3",
        "topico": "calculo diferencial"
    },
    {
        "enunciado": "Evalúa la integral indefinida",
        "ejercicio": "\\int (2x + 3) dx",
        "respuesta_correcta": "x^2 + 3x + C",
        "alternativa_incorrecta1": "2x^2 + 3x + C",
        "alternativa_incorrecta2": "x^2 + 3 + C",
        "topico": "calculo integral"
    },
    {
        "enunciado": "Calcula el límite de la función racional",
        "ejercicio": "\\lim_{x \\to 1} \\frac{x^2 - 1}{x - 1}",
        "respuesta_correcta": "2",
        "alternativa_incorrecta1": "0",
        "alternativa_incorrecta2": "1",
        "topico": "calculo infinitesimal"
    },
    {
        "enunciado": "Encuentra la derivada usando la regla del producto",
        "ejercicio": "f(x) = (x^2 + 1)(x - 3)",
        "respuesta_correcta": "f'(x) = 3x^2 - 6x + 1",
        "alternativa_incorrecta1": "f'(x) = 2x(x - 3)",
        "alternativa_incorrecta2": "f'(x) = (x^2 + 1) + (x - 3)",
        "topico": "calculo diferencial"
    },
    {
        "enunciado": "Resuelve la integral definida",
        "ejercicio": "\\int_0^1 (3x^2) dx",
        "respuesta_correcta": "1",
        "alternativa_incorrecta1": "0",
        "alternativa_incorrecta2": "3",
        "topico": "calculo integral"
    },
    {
        "enunciado": "Determina si el límite existe",
        "ejercicio": "\\lim_{x \\to 0} \\frac{\\sin x}{x}",
        "respuesta_correcta": "1",
        "alternativa_incorrecta1": "0",
        "alternativa_incorrecta2": "\\infty",
        "topico": "calculo infinitesimal"
    },
    {
        "enunciado": "Aplica la regla de la cadena para derivar",
        "ejercicio": "f(x) = \\sin(3x)",
        "respuesta_correcta": "f'(x) = 3\\cos(3x)",
        "alternativa_incorrecta1": "f'(x) = \\cos(3x)",
        "alternativa_incorrecta2": "f'(x) = 3\\sin(3x)",
        "topico": "calculo diferencial"
    },
    {
        "enunciado": "Integra usando sustitución simple",
        "ejercicio": "\\int \\cos(2x) dx",
        "respuesta_correcta": "\\frac{1}{2}\\sin(2x) + C",
        "alternativa_incorrecta1": "\\sin(2x) + C",
        "alternativa_incorrecta2": "2\\sin(2x) + C",
        "topico": "calculo integral"
    },
    {
        "enunciado": "Calcula el límite al infinito",
        "ejercicio": "\\lim_{x \\to \\infty} \\frac{2x^2 + 3x}{x^2 - 1}",
        "respuesta_correcta": "2",
        "alternativa_incorrecta1": "0",
        "alternativa_incorrecta2": "\\infty",
        "topico": "calculo infinitesimal"
    },
    {
        "enunciado": "Deriva una función exponencial",
        "ejercicio": "f(x) = e^{2x}",
        "respuesta_correcta": "f'(x) = 2e^{2x}",
        "alternativa_incorrecta1": "f'(x) = e^{2x}",
        "alternativa_incorrecta2": "f'(x) = 2e^{x}",
        "topico": "calculo diferencial"
    },
    {
        "enunciado": "Resuelve la integral de una potencia",
        "ejercicio": "\\int x^3 dx",
        "respuesta_correcta": "\\frac{x^4}{4} + C",
        "alternativa_incorrecta1": "3x^2 + C",
        "alternativa_incorrecta2": "x^4 + C",
        "topico": "calculo integral"
    },
    {
        "enunciado": "Límite por factorización",
        "ejercicio": "\\lim_{x \\to 3} \\frac{x^2 - 9}{x - 3}",
        "respuesta_correcta": "6",
        "alternativa_incorrecta1": "0",
        "alternativa_incorrecta2": "3",
        "topico": "calculo infinitesimal"
    },
    {
        "enunciado": "Derivada de función logarítmica",
        "ejercicio": "f(x) = \\ln(5x)",
        "respuesta_correcta": "f'(x) = \\frac{1}{x}",
        "alternativa_incorrecta1": "f'(x) = \\frac{5}{x}",
        "alternativa_incorrecta2": "f'(x) = \\frac{1}{5x}",
        "topico": "calculo diferencial"
    },
    {
        "enunciado": "Integral definida con límites",
        "ejercicio": "\\int_1^2 (4x) dx",
        "respuesta_correcta": "6",
        "alternativa_incorrecta1": "4",
        "alternativa_incorrecta2": "8",
        "topico": "calculo integral"
    },
    {
        "enunciado": "Límite trigonométrico fundamental",
        "ejercicio": "\\lim_{x \\to 0} \\frac{1 - \\cos x}{x}",
        "respuesta_correcta": "0",
        "alternativa_incorrecta1": "1",
        "alternativa_incorrecta2": "\\infty",
        "topico": "calculo infinitesimal"
    },
    {
        "enunciado": "Derivada de función trigonométrica",
        "ejercicio": "f(x) = \\tan(x)",
        "respuesta_correcta": "f'(x) = \\sec^2(x)",
        "alternativa_incorrecta1": "f'(x) = \\cos(x)",
        "alternativa_incorrecta2": "f'(x) = -\\sin(x)",
        "topico": "calculo diferencial"
    },
    {
        "enunciado": "Integral de función exponencial",
        "ejercicio": "\\int e^{3x} dx",
        "respuesta_correcta": "\\frac{1}{3}e^{3x} + C",
        "alternativa_incorrecta1": "e^{3x} + C",
        "alternativa_incorrecta2": "3e^{3x} + C",
        "topico": "calculo integral"
    },
    {
        "enunciado": "Límite lateral por la derecha",
        "ejercicio": "\\lim_{x \\to 0^+} \\frac{1}{x}",
        "respuesta_correcta": "\\infty",
        "alternativa_incorrecta1": "0",
        "alternativa_incorrecta2": "1",
        "topico": "calculo infinitesimal"
    },
    {
        "enunciado": "Derivada de función raíz cuadrada",
        "ejercicio": "f(x) = \\sqrt{x}",
        "respuesta_correcta": "f'(x) = \\frac{1}{2\\sqrt{x}}",
        "alternativa_incorrecta1": "f'(x) = \\frac{1}{\\sqrt{x}}",
        "alternativa_incorrecta2": "f'(x) = 2\\sqrt{x}",
        "topico": "calculo diferencial"
    },
    {
        "enunciado": "Integral de función racional",
        "ejercicio": "\\int \\frac{1}{x} dx",
        "respuesta_correcta": "\\ln|x| + C",
        "alternativa_incorrecta1": "\\frac{1}{x^2} + C",
        "alternativa_incorrecta2": "x + C",
        "topico": "calculo integral"
    },
    {
        "enunciado": "Límite de función por partes",
        "ejercicio": "\\lim_{x \\to 0} f(x) \\text{ donde } f(x) = \\begin{cases} x^2 & \\text{si } x < 0 \\\\ x + 1 & \\text{si } x \\geq 0 \\end{cases}",
        "respuesta_correcta": "1",
        "alternativa_incorrecta1": "0",
        "alternativa_incorrecta2": "\\text{No existe}",
        "topico": "calculo infinitesimal"
    },
    {
        "enunciado": "Derivada usando regla del cociente",
        "ejercicio": "f(x) = \\frac{x}{x^2 + 1}",
        "respuesta_correcta": "f'(x) = \\frac{1 - x^2}{(x^2 + 1)^2}",
        "alternativa_incorrecta1": "f'(x) = \\frac{1}{2x}",
        "alternativa_incorrecta2": "f'(x) = \\frac{x^2 + 1 - x}{(x^2 + 1)^2}",
        "topico": "calculo diferencial"
    },
    {
        "enunciado": "Integral por sustitución",
        "ejercicio": "\\int 2x\\sqrt{x^2 + 1} dx",
        "respuesta_correcta": "\\frac{2}{3}(x^2 + 1)^{3/2} + C",
        "alternativa_incorrecta1": "2x\\sqrt{x^2 + 1} + C",
        "alternativa_incorrecta2": "\\frac{1}{2}(x^2 + 1)^{3/2} + C",
        "topico": "calculo integral"
    },
    {
        "enunciado": "Límite de sucesión",
        "ejercicio": "\\lim_{n \\to \\infty} \\frac{3n^2 + 2n}{n^2 - 5}",
        "respuesta_correcta": "3",
        "alternativa_incorrecta1": "0",
        "alternativa_incorrecta2": "\\infty",
        "topico": "calculo infinitesimal"
    },
    {
        "enunciado": "Derivada implícita básica",
        "ejercicio": "x^2 + y^2 = 25",
        "respuesta_correcta": "\\frac{dy}{dx} = -\\frac{x}{y}",
        "alternativa_incorrecta1": "\\frac{dy}{dx} = \\frac{x}{y}",
        "alternativa_incorrecta2": "\\frac{dy}{dx} = -\\frac{y}{x}",
        "topico": "calculo diferencial"
    },
    {
        "enunciado": "Integral de función trigonométrica",
        "ejercicio": "\\int \\sin(x) dx",
        "respuesta_correcta": "-\\cos(x) + C",
        "alternativa_incorrecta1": "\\cos(x) + C",
        "alternativa_incorrecta2": "\\sin(x) + C",
        "topico": "calculo integral"
    },
    {
        "enunciado": "Continuidad de función",
        "ejercicio": "f(x) = \\frac{x^2 - 4}{x - 2} \\text{ en } x = 2",
        "respuesta_correcta": "\\text{No es continua (discontinuidad evitable)}",
        "alternativa_incorrecta1": "\\text{Es continua}",
        "alternativa_incorrecta2": "\\text{Discontinuidad infinita}",
        "topico": "calculo infinitesimal"
    },
    {
        "enunciado": "Derivada de orden superior",
        "ejercicio": "f(x) = x^3 - 2x^2 + x \\text{, encuentra } f''(x)",
        "respuesta_correcta": "f''(x) = 6x - 4",
        "alternativa_incorrecta1": "f''(x) = 3x^2 - 4x",
        "alternativa_incorrecta2": "f''(x) = 6x",
        "topico": "calculo diferencial"
    },
    {
        "enunciado": "Integral definida con función valor absoluto",
        "ejercicio": "\\int_{-1}^1 |x| dx",
        "respuesta_correcta": "1",
        "alternativa_incorrecta1": "0",
        "alternativa_incorrecta2": "2",
        "topico": "calculo integral"
    },
    {
        "enunciado": "Límite con valor absoluto",
        "ejercicio": "\\lim_{x \\to 0} \\frac{|x|}{x}",
        "respuesta_correcta": "\\text{No existe}",
        "alternativa_incorrecta1": "0",
        "alternativa_incorrecta2": "1",
        "topico": "calculo infinitesimal"
    },
    {
        "enunciado": "Derivada de función inversa",
        "ejercicio": "\\text{Si } f(x) = x^3 \\text{, encuentra } (f^{-1})'(8)",
        "respuesta_correcta": "\\frac{1}{12}",
        "alternativa_incorrecta1": "12",
        "alternativa_incorrecta2": "\\frac{1}{3}",
        "topico": "calculo diferencial"
    },
    {
        "enunciado": "Integración por partes básica",
        "ejercicio": "\\int x e^x dx",
        "respuesta_correcta": "xe^x - e^x + C",
        "alternativa_incorrecta1": "xe^x + C",
        "alternativa_incorrecta2": "e^x + C",
        "topico": "calculo integral"
    },
    {
        "enunciado": "Límite de función compuesta",
        "ejercicio": "\\lim_{x \\to 0} \\sqrt{1 + x}",
        "respuesta_correcta": "1",
        "alternativa_incorrecta1": "0",
        "alternativa_incorrecta2": "\\infty",
        "topico": "calculo infinitesimal"
    },
    {
        "enunciado": "Derivada de función paramétrica",
        "ejercicio": "x = t^2, y = t^3 \\text{, encuentra } \\frac{dy}{dx}",
        "respuesta_correcta": "\\frac{3t}{2}",
        "alternativa_incorrecta1": "\\frac{2t}{3}",
        "alternativa_incorrecta2": "\\frac{3}{2t}",
        "topico": "calculo diferencial"
    },
    {
        "enunciado": "Integral de función racional con división",
        "ejercicio": "\\int \\frac{x^2 + 1}{x} dx",
        "respuesta_correcta": "\\frac{x^2}{2} + \\ln|x| + C",
        "alternativa_incorrecta1": "x + \\ln|x| + C",
        "alternativa_incorrecta2": "\\frac{x^3}{3} + x + C",
        "topico": "calculo integral"
    },
    {
        "enunciado": "Límite con cambio de variable",
        "ejercicio": "\\lim_{x \\to 4} \\frac{\\sqrt{x} - 2}{x - 4}",
        "respuesta_correcta": "\\frac{1}{4}",
        "alternativa_incorrecta1": "0",
        "alternativa_incorrecta2": "\\frac{1}{2}",
        "topico": "calculo infinitesimal"
    },
    {
        "enunciado": "Derivada de función exponencial compuesta",
        "ejercicio": "f(x) = e^{x^2}",
        "respuesta_correcta": "f'(x) = 2xe^{x^2}",
        "alternativa_incorrecta1": "f'(x) = e^{x^2}",
        "alternativa_incorrecta2": "f'(x) = 2e^{x^2}",
        "topico": "calculo diferencial"
    },
    {
        "enunciado": "Integral trigonométrica con identidad",
        "ejercicio": "\\int \\cos^2(x) dx",
        "respuesta_correcta": "\\frac{x}{2} + \\frac{\\sin(2x)}{4} + C",
        "alternativa_incorrecta1": "\\sin(x) + C",
        "alternativa_incorrecta2": "\\frac{\\cos^3(x)}{3} + C",
        "topico": "calculo integral"
    },
    {
        "enunciado": "Límite de función a trozos",
        "ejercicio": "\\lim_{x \\to 1} f(x) \\text{ donde } f(x) = \\begin{cases} 2x & \\text{si } x < 1 \\\\ x^2 + 1 & \\text{si } x \\geq 1 \\end{cases}",
        "respuesta_correcta": "2",
        "alternativa_incorrecta1": "1",
        "alternativa_incorrecta2": "\\text{No existe}",
        "topico": "calculo infinitesimal"
    },
    {
        "enunciado": "Derivada de función logarítmica natural",
        "ejercicio": "f(x) = \\ln(\\sin x)",
        "respuesta_correcta": "f'(x) = \\cot x",
        "alternativa_incorrecta1": "f'(x) = \\frac{1}{\\sin x}",
        "alternativa_incorrecta2": "f'(x) = \\tan x",
        "topico": "calculo diferencial"
    },
    {
        "enunciado": "Integral por fracciones parciales simple",
        "ejercicio": "\\int \\frac{1}{x(x+1)} dx",
        "respuesta_correcta": "\\ln\\left|\\frac{x}{x+1}\\right| + C",
        "alternativa_incorrecta1": "\\ln|x(x+1)| + C",
        "alternativa_incorrecta2": "\\frac{1}{x} + \\frac{1}{x+1} + C",
        "topico": "calculo integral"
    },
    {
        "enunciado": "Límite con radicales",
        "ejercicio": "\\lim_{x \\to 0} \\frac{\\sqrt{x+1} - 1}{x}",
        "respuesta_correcta": "\\frac{1}{2}",
        "alternativa_incorrecta1": "0",
        "alternativa_incorrecta2": "1",
        "topico": "calculo infinitesimal"
    },
    {
        "enunciado": "Derivada de función arco tangente",
        "ejercicio": "f(x) = \\arctan(2x)",
        "respuesta_correcta": "f'(x) = \\frac{2}{1 + 4x^2}",
        "alternativa_incorrecta1": "f'(x) = \\frac{1}{1 + 4x^2}",
        "alternativa_incorrecta2": "f'(x) = \\frac{2}{1 + x^2}",
        "topico": "calculo diferencial"
    },
    {
        "enunciado": "Integral de función secante al cuadrado",
        "ejercicio": "\\int \\sec^2(x) dx",
        "respuesta_correcta": "\\tan(x) + C",
        "alternativa_incorrecta1": "\\sec(x) + C",
        "alternativa_incorrecta2": "\\cot(x) + C",
        "topico": "calculo integral"
    },
    {
        "enunciado": "Límite de función racional con grado mayor abajo",
        "ejercicio": "\\lim_{x \\to \\infty} \\frac{3x + 2}{x^2 - 1}",
        "respuesta_correcta": "0",
        "alternativa_incorrecta1": "\\infty",
        "alternativa_incorrecta2": "3",
        "topico": "calculo infinitesimal"
    },
    {
        "enunciado": "Derivada usando diferenciación logarítmica",
        "ejercicio": "f(x) = x^x",
        "respuesta_correcta": "f'(x) = x^x(\\ln x + 1)",
        "alternativa_incorrecta1": "f'(x) = xx^{x-1}",
        "alternativa_incorrecta2": "f'(x) = x^x \\ln x",
        "topico": "calculo diferencial"
    },
    {
        "enunciado": "Integral definida con sustitución",
        "ejercicio": "\\int_0^1 x\\sqrt{1 + x^2} dx",
        "respuesta_correcta": "\\frac{\\sqrt{8} - 1}{3}",
        "alternativa_incorrecta1": "\\frac{1}{2}",
        "alternativa_incorrecta2": "\\sqrt{2} - 1",
        "topico": "calculo integral"
    },
    {
        "enunciado": "Límite de función con exponente",
        "ejercicio": "\\lim_{x \\to 0} (1 + x)^{1/x}",
        "respuesta_correcta": "e",
        "alternativa_incorrecta1": "1",
        "alternativa_incorrecta2": "\\infty",
        "topico": "calculo infinitesimal"
    },
    {
        "enunciado": "Derivada de función hiperbólica",
        "ejercicio": "f(x) = \\sinh(x)",
        "respuesta_correcta": "f'(x) = \\cosh(x)",
        "alternativa_incorrecta1": "f'(x) = -\\sinh(x)",
        "alternativa_incorrecta2": "f'(x) = \\tanh(x)",
        "topico": "calculo diferencial"
    },
    {
        "enunciado": "Integral de función con valor absoluto",
        "ejercicio": "\\int |x - 1| dx",
        "respuesta_correcta": "\\begin{cases} \\frac{x^2}{2} - x + C & \\text{si } x < 1 \\\\ -\\frac{x^2}{2} + x + C & \\text{si } x \\geq 1 \\end{cases}",
        "alternativa_incorrecta1": "x|x - 1| + C",
        "alternativa_incorrecta2": "\\frac{(x-1)|x-1|}{2} + C",
        "topico": "calculo integral"
    },
    {
        "enunciado": "Límite de función con logaritmo",
        "ejercicio": "\\lim_{x \\to 1} \\frac{\\ln x}{x - 1}",
        "respuesta_correcta": "1",
        "alternativa_incorrecta1": "0",
        "alternativa_incorrecta2": "\\infty",
        "topico": "calculo infinitesimal"
    },
    {
        "enunciado": "Derivada parcial básica",
        "ejercicio": "f(x,y) = x^2y + y^3",
        "respuesta_correcta": "\\frac{\\partial f}{\\partial x} = 2xy",
        "alternativa_incorrecta1": "\\frac{\\partial f}{\\partial x} = x^2 + 3y^2",
        "alternativa_incorrecta2": "\\frac{\\partial f}{\\partial x} = 2x + y",
        "topico": "calculo diferencial"
    },
    {
        "enunciado": "Integral impropia tipo 1",
        "ejercicio": "\\int_1^\\infty \\frac{1}{x^2} dx",
        "respuesta_correcta": "1",
        "alternativa_incorrecta1": "\\infty",
        "alternativa_incorrecta2": "0",
        "topico": "calculo integral"
    }
    ]

    for ej in ejercicios_calculo:
        ejercicio = Ejercicios(
            enunciado = ej['enunciado'],
            ejercicio = ej['ejercicio'],
            respuesta_correcta = ej['respuesta_correcta'],
            alternativa1 = ej['alternativa_incorrecta1'],
            alternativa2 = ej['alternativa_incorrecta2'],
            topico = ej['topico']
        )
        ejercicio.save()


def limpiar_ejercicios(apps, schema_editor):
    ejercicios = apps.get_model('ejercicios', 'Ejercicios') 
    ejercicios.objects.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(cargar_ejercicios, limpiar_ejercicios)
    ]
