# Generated by Django 5.2.7 on 2025-11-06 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0002_auto_20251030_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pruebas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_completada', models.DateTimeField(null=True)),
                ('completada', models.BooleanField(default=False)),
                ('correctas', models.IntegerField(default=0)),
                ('incorrectas', models.IntegerField(default=0)),
                ('cantidad_preguntas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pregunta', models.IntegerField()),
                ('respuesta', models.CharField(max_length=255, null=True)),
                ('fecha_respuesta', models.DateTimeField(null=True)),
                ('es_correcta', models.BooleanField(null=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ejercicios.ejercicios')),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ejercicios.pruebas')),
            ],
        ),
        migrations.CreateModel(
            name='Alternativas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('formula', models.CharField(max_length=255)),
                ('seleccionada', models.BooleanField(default=False)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ejercicios.preguntas')),
            ],
        ),
    ]
